name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Application
    uses: ./.github/workflows/reusable-test.yml