name: Publish Container

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish Application
    uses: ./.github/workflows/reusable-publish.yml